run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - hack
    - vendor

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - govet
    - gocyclo
    - goconst
    - ineffassign
    - goimports
    - misspell
    - unparam
    - typecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0