apiVersion: v1
kind: Service
metadata:
  name: {{ include "yuk.fullname" . }}-metrics
  labels:
    {{- include "yuk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "yuk.selectorLabels" . | nindent 4 }}