{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yuk.serviceAccountName" . }}
  labels:
    {{- include "yuk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.aws.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsa.roleArn }}
  {{- end }}
{{- end }}