apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: default
type: Opaque
data:
  # Base64 encoded GitHub Personal Access Token
  # Replace with: echo -n "your-github-token" | base64
  token: Z2hwX3lvdXJfZ2l0aHViX3Rva2VuX2hlcmU=